import { prisma } from '@/lib/prisma';
// Import the type generated by Prisma
import type { VisitLog } from '@prisma/client';

async function getStats() {
  try {
    const [totalVisits, uniquePagesResult, recentVisits] = await prisma.$transaction([
      prisma.visitLog.count(),
      prisma.visitLog.findMany({ select: { pageUrl: true }, distinct: ['pageUrl'] }),
      prisma.visitLog.findMany({ orderBy: { visitTime: 'desc' }, take: 5 }),
    ]);
    return {
      totalVisits,
      uniquePages: uniquePagesResult.length,
      recentVisits,
    };
  } catch (error) {
    console.error("Failed to fetch stats:", error);
    return { totalVisits: 0, uniquePages: 0, recentVisits: [] };
  }
}

export default async function AdminLogsPage({
  searchParams,
}: {
  searchParams?: { search?: string; };
}) {
  const searchQuery = searchParams?.search || '';

  const logs: VisitLog[] = await prisma.visitLog.findMany({
    where: {
      pageUrl: { contains: searchQuery, mode: 'insensitive' },
    },
    orderBy: { visitTime: 'desc' },
    take: 100,
  });

  const stats = await getStats();

  return (
    <div className="w-full">
      <h1 className="text-3xl font-bold mb-4">Magical Space - Admin Dashboard</h1>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-gray-500 text-sm font-medium">Total Visits</h3>
          <p className="text-3xl font-semibold">{stats.totalVisits.toLocaleString()}</p>
        </div>
        <div className="bg-white p-6 rounded-lg shadow">
          <h3 className="text-gray-500 text-sm font-medium">Unique Pages</h3>
          <p className="text-3xl font-semibold">{stats.uniquePages.toLocaleString()}</p>
        </div>
        <div className="bg-white p-6 rounded-lg shadow">
           <h3 className="text-gray-500 text-sm font-medium">Recent Visits</h3>
           <ul className="text-sm mt-2 space-y-1">
             {stats.recentVisits.map((visit: VisitLog) => (
               <li key={visit.id} className="truncate" title={visit.pageUrl}>
                 {new URL(visit.pageUrl).pathname || '/'}
               </li>
             ))}
           </ul>
        </div>
      </div>

      <div className="bg-white p-6 rounded-lg shadow">
        <h2 className="text-2xl font-semibold mb-4">Visit Logs (Last 100)</h2>
        <form method="GET" className="mb-4">
          <div className="flex">
            <input
              type="text"
              name="search"
              defaultValue={searchQuery}
              placeholder="Filter by Page URL..."
              className="w-full px-3 py-2 border border-gray-300 rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <button
              type="submit"
              className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-r-md hover:bg-blue-700"
            >
              Search
            </button>
          </div>
        </form>

        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Page URL</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Visit Time</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">IP Address</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">User Agent</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {/* FIX: Add the VisitLog type to the 'log' parameter */}
              {logs.map((log: VisitLog) => (
                <tr key={log.id}>
                  <td className="px-6 py-4 text-sm text-gray-900 truncate max-w-xs" title={log.pageUrl}>{log.pageUrl}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{new Date(log.visitTime).toLocaleString()}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{log.ipAddress}</td>
                  <td className="px-6 py-4 text-sm text-gray-500 truncate max-w-xs" title={log.userAgent ?? ''}>{log.userAgent}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {logs.length === 0 && <p className="text-center text-gray-500 mt-4">No logs found.</p>}
      </div>
    </div>
  );
}

export const dynamic = 'force-dynamic';